#!/usr/bin/env bash
hosts="localhost"
port=22
user=$USER
file=""
path=""

#!/bin/bash
while getopts "h:p:u:f:P:" arg
do
    case $arg in
    h)
        hosts=$OPTARG
        ;;
    p)
        port=$OPTARG
        ;;
    u)
        user=$OPTARG
        ;;
    f)
        file=$OPTARG
        ;;
    P)
        path=$OPTARG
        ;;
    esac
done

if [ -z "$file" ]; then
    echo "please specify a file"
    exit
fi

if [ -z "$path" ]; then
    echo "please specify a path"
    exit
fi

for host in $hosts; do
    shell_cmd="scp -r -P $port $file $user@$host:$path"
    echo -e "\033[32m*** $shell_cmd ***\033[0m"
    $shell_cmd
done
